/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var grammar = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,8],$V1=[1,14],$V2=[1,15],$V3=[1,16],$V4=[1,17],$V5=[1,18],$V6=[1,11],$V7=[1,13],$V8=[5,22],$V9=[5,10,11,22,28],$Va=[1,26],$Vb=[1,25],$Vc=[1,27],$Vd=[1,28],$Ve=[1,29],$Vf=[1,30],$Vg=[1,31],$Vh=[1,32],$Vi=[21,30,31],$Vj=[10,11],$Vk=[22,28];
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"program":3,"expression":4,"EOF":5,"MATH_EXPRESSION":6,"SEQUENCE":7,"MATH_EX":8,"SEQUENCE_ITEMS":9,"MATHEMATICAL_OPERATOR":10,"COMPARISION_OPERATOR":11,"TEXT":12,"STRING":13,"LOGICAL_OPERATOR":14,"DATE_FUNCTION":15,"LOGIC_FUNCTION":16,"MATH_FUNCTION":17,"PERIOD_FUNCTION":18,"STRING_FUNCTION":19,"QUOTE":20,"\"":21,"COMMA":22,"FUNCTION":23,"FIELD":24,"FUNCTION_NAME":25,"(":26,"ARGS":27,")":28,"[":29,"]":30,"DOT":31,"USERENTITY":32,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",10:"MATHEMATICAL_OPERATOR",11:"COMPARISION_OPERATOR",13:"STRING",14:"LOGICAL_OPERATOR",15:"DATE_FUNCTION",16:"LOGIC_FUNCTION",17:"MATH_FUNCTION",18:"PERIOD_FUNCTION",19:"STRING_FUNCTION",21:"\"",22:"COMMA",26:"(",28:")",29:"[",30:"]",31:"DOT",32:"USERENTITY"},
productions_: [0,[3,2],[4,1],[4,1],[8,3],[8,3],[6,3],[12,1],[12,1],[12,1],[12,1],[12,1],[12,1],[12,1],[12,1],[20,3],[7,1],[7,3],[9,1],[9,1],[9,1],[9,1],[23,4],[25,1],[25,1],[25,1],[25,1],[25,1],[27,1],[27,3],[24,3],[24,5],[24,5]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
console.log(JSON.stringify($$[$0-1], null, 4)); return $$[$0-1]; 
break;
case 4: case 5:
this.$ = {node: 'MATHEMATICAL_OPERATOR', type: $$[$0-1], left: $$[$0-2], right: $$[$0]}
break;
case 6:
this.$ = {node: 'COMPARISION_OPERATOR', type: $$[$0-1], left: $$[$0-2], right: $$[$0]}
break;
case 15:
this.$ = {node: 'QUOTE', content: $$[$0-1]}
break;
case 16: case 28:
this.$ = [$$[$0]]
break;
case 17: case 29:
$$[$0-2].push($$[$0]); this.$ = $$[$0-2]
break;
case 22:
this.$ = {node: $$[$0-3], args: $$[$0-1]}
break;
case 23:
this.$ = $$[$0] + '-DATE_FUNCTION'
break;
case 24:
this.$ = $$[$0] + '-LOGIC_FUNCTION'
break;
case 25:
this.$ = $$[$0] + '-MATH_FUNCTION'
break;
case 26:
this.$ = $$[$0] + '-PERIOD_FUNCTION'
break;
case 27:
this.$ = $$[$0] + '-STRING_FUNCTION'
break;
case 30:
this.$ = {node: 'FIELD_NO_ENTITY', field: $$[$0-1]}
break;
case 31:
this.$ = {node: 'FIELD_AND_ENTITY', field: $$[$0-1], entity: $$[$0-3]}
break;
case 32:
this.$ = {node: 'FIELD_AND_USERENTITY', field: $$[$0-1], userentity: $$[$0-3]}
break;
}
},
table: [{3:1,4:2,6:3,7:4,8:5,9:6,13:$V0,15:$V1,16:$V2,17:$V3,18:$V4,19:$V5,20:7,21:$V6,23:9,24:10,25:12,29:$V7},{1:[3]},{5:[1,19]},{5:[2,2]},{5:[2,3],22:[1,20]},{10:[1,22],11:[1,21]},o($V8,[2,16],{10:[1,23]}),o($V9,[2,18]),o($V9,[2,19]),o($V9,[2,20]),o($V9,[2,21]),{11:$Va,12:24,13:$Vb,14:$Vc,15:$Vd,16:$Ve,17:$Vf,18:$Vg,19:$Vh},{26:[1,33]},{11:$Va,12:34,13:$Vb,14:$Vc,15:$Vd,16:$Ve,17:$Vf,18:$Vg,19:$Vh,32:[1,35]},{26:[2,23]},{26:[2,24]},{26:[2,25]},{26:[2,26]},{26:[2,27]},{1:[2,1]},{9:36,13:$V0,15:$V1,16:$V2,17:$V3,18:$V4,19:$V5,20:7,21:$V6,23:9,24:10,25:12,29:$V7},{9:37,13:$V0,15:$V1,16:$V2,17:$V3,18:$V4,19:$V5,20:7,21:$V6,23:9,24:10,25:12,29:$V7},{9:38,13:$V0,15:$V1,16:$V2,17:$V3,18:$V4,19:$V5,20:7,21:$V6,23:9,24:10,25:12,29:$V7},{9:39,13:$V0,15:$V1,16:$V2,17:$V3,18:$V4,19:$V5,20:7,21:$V6,23:9,24:10,25:12,29:$V7},{21:[1,40]},o($Vi,[2,7]),o($Vi,[2,8]),o($Vi,[2,9]),o($Vi,[2,10]),o($Vi,[2,11]),o($Vi,[2,12]),o($Vi,[2,13]),o($Vi,[2,14]),{9:42,13:$V0,15:$V1,16:$V2,17:$V3,18:$V4,19:$V5,20:7,21:$V6,23:9,24:10,25:12,27:41,29:$V7},{30:[1,43],31:[1,44]},{31:[1,45]},o($V8,[2,17]),{5:[2,6]},o($Vj,[2,5]),o($Vj,[2,4]),o($V9,[2,15]),{22:[1,47],28:[1,46]},o($Vk,[2,28]),o($V9,[2,30]),{11:$Va,12:48,13:$Vb,14:$Vc,15:$Vd,16:$Ve,17:$Vf,18:$Vg,19:$Vh},{11:$Va,12:49,13:$Vb,14:$Vc,15:$Vd,16:$Ve,17:$Vf,18:$Vg,19:$Vh},o($V9,[2,22]),{9:50,13:$V0,15:$V1,16:$V2,17:$V3,18:$V4,19:$V5,20:7,21:$V6,23:9,24:10,25:12,29:$V7},{30:[1,51]},{30:[1,52]},o($Vk,[2,29]),o($V9,[2,31]),o($V9,[2,32])],
defaultActions: {3:[2,2],14:[2,23],15:[2,24],16:[2,25],17:[2,26],18:[2,27],19:[2,1],37:[2,6]},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function (match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex() {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin(condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules() {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState(condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:return 10
break;
case 1:return 10
break;
case 2:return 10
break;
case 3:return 10
break;
case 4:return 10
break;
case 5:return 11
break;
case 6:return 11
break;
case 7:return 11
break;
case 8:return 11
break;
case 9:return 11
break;
case 10:return 11
break;
case 11:return 11
break;
case 12:return 11
break;
case 13:return 11
break;
case 14:return 11
break;
case 15:return 11
break;
case 16:return 11
break;
case 17:return 14
break;
case 18:return 14
break;
case 19:return 14
break;
case 20:return 15
break;
case 21:return 15
break;
case 22:return 15
break;
case 23:return 15
break;
case 24:return 15
break;
case 25:return 15
break;
case 26:return 15
break;
case 27:return 15
break;
case 28:return 15
break;
case 29:return 15
break;
case 30:return 15
break;
case 31:return 15
break;
case 32:return 15
break;
case 33:return 15
break;
case 34:return 15
break;
case 35:return 15
break;
case 36:return 15
break;
case 37:return 15
break;
case 38:return 15
break;
case 39:return 15
break;
case 40:return 15
break;
case 41:return 15
break;
case 42:return 15
break;
case 43:return 15
break;
case 44:return 15
break;
case 45:return 15
break;
case 46:return 15
break;
case 47:return 16
break;
case 48:return 16
break;
case 49:return 16
break;
case 50:return 16
break;
case 51:return 17
break;
case 52:return 17
break;
case 53:return 17
break;
case 54:return 17
break;
case 55:return 17
break;
case 56:return 17
break;
case 57:return 17
break;
case 58:return 17
break;
case 59:return 17
break;
case 60:return 17
break;
case 61:return 17
break;
case 62:return 18
break;
case 63:return 18
break;
case 64:return 18
break;
case 65:return 18
break;
case 66:return 18
break;
case 67:return 18
break;
case 68:return 18
break;
case 69:return 18
break;
case 70:return 18
break;
case 71:return 18
break;
case 72:return 18
break;
case 73:return 18
break;
case 74:return 18
break;
case 75:return 18
break;
case 76:return 18
break;
case 77:return 18
break;
case 78:return 18
break;
case 79:return 18
break;
case 80:return 18
break;
case 81:return 18
break;
case 82:return 19
break;
case 83:return 19
break;
case 84:return 19
break;
case 85:return 32
break;
case 86:/*ignore*/
break;
case 87://return 'SPACE'
break;
case 88:return 13
break;
case 89:return 26
break;
case 90:return 28
break;
case 91:return 29
break;
case 92:return 30
break;
case 93:return 21
break;
case 94:return 22
break;
case 95:return 31
break;
case 96:return 5
break;
}
},
rules: [/^(?:\+)/,/^(?:-)/,/^(?:\*)/,/^(?:\/)/,/^(?:\^)/,/^(?:=)/,/^(?:<>)/,/^(?:>)/,/^(?:>=)/,/^(?:<)/,/^(?:<=)/,/^(?:LIKE\b)/,/^(?:NOT LIKE\b)/,/^(?:IN\b)/,/^(?:NOT IN\b)/,/^(?:BETWEEN\b)/,/^(?:NOT BETWEEN\b)/,/^(?:AND\b)/,/^(?:OR\b)/,/^(?:NOT\b)/,/^(?:AddDays\b)/,/^(?:AddMonths\b)/,/^(?:AddYears\b)/,/^(?:Date\b)/,/^(?:Datetime\b)/,/^(?:Day\b)/,/^(?:ElapsedDays\b)/,/^(?:ElapsedMonths\b)/,/^(?:ElapsedYears\b)/,/^(?:FirstDayInPeriod\b)/,/^(?:Hour\b)/,/^(?:LastDayInPeriod\b)/,/^(?:Max\b)/,/^(?:Min\b)/,/^(?:Minute\b)/,/^(?:Month\b)/,/^(?:Now\b)/,/^(?:PeriodForDate\b)/,/^(?:PeriodNumberForDate\b)/,/^(?:PeriodYearForDate\b)/,/^(?:Second\b)/,/^(?:SubtractDays\b)/,/^(?:SubtractMonths\b)/,/^(?:SubtractYears\b)/,/^(?:Today\b)/,/^(?:Weekday\b)/,/^(?:Year\b)/,/^(?:If\b)/,/^(?:IsAlpha\b)/,/^(?:IsAlphanumeric\b)/,/^(?:IsEmpty\b)/,/^(?:Abs\b)/,/^(?:Average\b)/,/^(?:Ceiling\b)/,/^(?:Floor\b)/,/^(?:Max\b)/,/^(?:Min\b)/,/^(?:Mod\b)/,/^(?:Round\b)/,/^(?:RoundDown\b)/,/^(?:RoundUp\b)/,/^(?:Sqrt\b)/,/^(?:AddPeriods\b)/,/^(?:CorrespondingPeriod\b)/,/^(?:FirstPeriodInCorrespondingPeriod\b)/,/^(?:LastPeriodInCorrespondingPeriod\b)/,/^(?:Max\b)/,/^(?:Min\b)/,/^(?:Period\b)/,/^(?:PeriodNumberForPeriod\b)/,/^(?:PeriodYearForPeriod\b)/,/^(?:SubtractPeriods\b)/,/^(?:String\b)/,/^(?:Concatenate\b)/,/^(?:Find\b)/,/^(?:Left\b)/,/^(?:Length\b)/,/^(?:Lower\b)/,/^(?:Max\b)/,/^(?:Mid\b)/,/^(?:Min\b)/,/^(?:Right\b)/,/^(?:Trim\b)/,/^(?:Upper\b)/,/^(?:Value\b)/,/^(?:Userentity\b)/,/^(?:\s*\n\s*)/,/^(?:\s+)/,/^(?:[a-zA-Z0-9_-\s]+)/,/^(?:\()/,/^(?:\))/,/^(?:\[)/,/^(?:\])/,/^(?:")/,/^(?:,)/,/^(?:\.)/,/^(?:$)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = grammar;
exports.Parser = grammar.Parser;
exports.parse = function () { return grammar.parse.apply(grammar, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}